# Site settings
title: UPitch
email: contact@upitch.co
description: > # this means to ignore newlines until "baseurl:"
  Save half the time on presentations with templates that only look good but get the ball rolling.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://upitch.co" # the base hostname & protocol for your site
twitter_username: upitchtemplates
github_username:

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
  - jemoji